---
- gather_facts: false
  hosts: localhost
  vars_files:
    - Server_Inventory_hosts.yml
  tasks:
  - name: Create a ticket in SNOW updated
    register: new_change_request
    snow_record:
      data:
        cmdb_ci: "{{item.configuration_item}}"
        u_environment: "{{item.environment}}"
        assignment_group: "{{item.assignment_group}}"
        assigned_to: "{{item.assigned_to}}"
        u_change_coordinator: "{{item.change_coordinator}}"
        start_date: "{{item.start_date}}"
        end_date: "{{item.end_date}}"
        short_description: "{{item.short_description}}"
        description: "{{item.description}}"
        implementation_plan: "{{item.implementation_plan}}"
        backout_plan: "{{item.backout_plan}}"
        test_plan: "{{item.test_plan}}"
        type: Normal
      instance: dev54182
      password: 009@Shreya
      state: present
      table: change_request
      username: admin
    with_items:
        - "{{ serverinventory }}"
#    register: new_change_request
#- debug: var=new_change_request.record.number
